[package]
name = "pinetime-rtfm"
version = "0.1.0"
authors = ["Danilo Bargen <mail@dbrgn.ch>"]
edition = "2018"

[dependencies]
cortex-m-rt = "0.6"
cortex-m-semihosting = "0.3"
nrf52832-hal = { version = "0.8", features = ["rt", "xxAA-package"], default-features = false }
panic-semihosting = "0.5"
